// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0hISNv8DVu3rO0U-SzMp37RtZxyTJySE',
    appId: '1:91333191859:web:1b192e74a0aa2b6017a8c6',
    messagingSenderId: '91333191859',
    projectId: 'sugarless-252ae',
    authDomain: 'sugarless-252ae.firebaseapp.com',
    storageBucket: 'sugarless-252ae.firebasestorage.app',
    measurementId: 'G-L5JQW0B42L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEnWSWDNlsUE-xOOtLTRxyrwQ9ZstdpOM',
    appId: '1:91333191859:android:30ff8af0930ed7cd17a8c6',
    messagingSenderId: '91333191859',
    projectId: 'sugarless-252ae',
    storageBucket: 'sugarless-252ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk4AgxkjnfjLfsENybXCiDcKa00KZwBgY',
    appId: '1:91333191859:ios:798b13ff8ee8793e17a8c6',
    messagingSenderId: '91333191859',
    projectId: 'sugarless-252ae',
    storageBucket: 'sugarless-252ae.firebasestorage.app',
    iosBundleId: 'com.yourcompany.template',
  );
}
